### ISSUE TITLE
Class decorators not applied to classes when they are exported

### ISSUE THREAD

**Issue by hswolff** [loganfsmyth/babel-plugin-transform-decorators-legacy#15]
Previously this worked in babel 5:

``` js
@connect()
export default class Page extends React.Component {

}
```

However it doesn't seem like this case is covered by this plugin. Curious if it's possible to add support for it?

**Comment by gpbl** [comment]
I couldn't get it working. Refactoring sometimes is easier:

``` js
class Page extends Component { /* ... */ }
export default connect()(Page)
```

**Comment by dtothefp** [comment]
@hswolff works for me. Maybe something wrong in your in implementation

**Comment by hswolff** [comment]
You're right @dtothefp! I just cleared react-native's packager cache and now it's working. Sorry about this! Damn :moneybag: got me. :(
