### ISSUE TITLE
Have any idea to remove decorator for testing

### ISSUE THREAD

**Issue by hank7444** [loganfsmyth/babel-plugin-transform-decorators-legacy#18]
```
@listensToClickOutside()

export default class myClass extends Component {

}
```

to

```
export default class myClass extends Component {

}
```

I read the babel-handbook and use 'babel-plugin-syntax-decorators'

![image](https://cloud.githubusercontent.com/assets/4727090/12775938/cf02f266-ca8c-11e5-9049-0e6f313462bc.png)

this is my import code:

![image](https://cloud.githubusercontent.com/assets/4727090/12776005/522bdbee-ca8d-11e5-99dc-da7edb2608e6.png)

and output: 

![image](https://cloud.githubusercontent.com/assets/4727090/12776008/61d24cb8-ca8d-11e5-8f6d-087af1a7e861.png)

I don't see any decorator...have any idea@@?

**Comment by mark-rushakoff** [comment]
Even though the decorator call doesn't seem to have shown up in your code, I was in a similar situation: I wanted to remove the decorator call altogether as well. My original use of decorators was different: I'm using it on functions in object literals.

But I was trying to achieve the same thing you mentioned - stripping out the call to the decorator alotogether, in production builds. The best I was able to do for a custom plugin was to remove the argument to the call to my decorator, like so:

``` js
{
  CallExpression: function(path) {
    var node = path.node;
    var callee = node.callee;
    if (callee.type === 'Identifier') {
       if (callee.name === THE_DECORATOR_NAME && node.arguments.length === 1) {
        console.log('Stripping out argument to ' + THE_DECORATOR_NAME);
        node.arguments.pop();
      }
    }
  }
}
```

I'm sure there was a better way to do this, but I didn't have time to improve it or learn a different approach. I hope maybe that helps you or gives you a starting point, though.

**Comment by loganfsmyth** [comment]
I'm sorry, does this have anything to do with this plugin, or are you looking for general support? Babel has its support channels here: https://github.com/babel/babel#looking-for-support
