### ISSUE TITLE
[Feature request] Support decorating static properties

### ISSUE THREAD

**Issue by elierotenberg** [loganfsmyth/babel-plugin-transform-decorators-legacy#2]
Disclaimer: **thanks a lot** for taking the time and effort to implement this, I know you tried your best to provide us with a tentative implementation regardless of the decorator spec being questioned at the time.

It seems that this implementation currently doesn't support decorating static properties; I couldn't find any reference to them in either the source or the tests. Do you plan to add support for them in the near future?

**Comment by loganfsmyth** [comment]
Good call, that was a total oversight on my part. I've just pushed 1.1.0 with support for static methods, but static class properties are still not supported. They will now throw a clear error message instead of compiling incorrectly however.

**Comment by loganfsmyth** [comment]
I will add support for them, it'll just require a bit more work so I can't right this minute.

**Comment by elierotenberg** [comment]
:+1:

**Comment by ide** [comment]
@loganfsmyth would you have an estimate of how much work is required to support static class properties (React uses these heavily)?

**Comment by loganfsmyth** [comment]
I'll just need to rework the ordering of things a bit. It's totally doable, just didn't have time this morning before work :)

**Comment by loganfsmyth** [comment]
I've just pushed 1.3.0 with static class property support.
