### ISSUE TITLE
[QUESTION] Is it possible to overwrite the method of the target?

### ISSUE THREAD

**Issue by ipeychev** [loganfsmyth/babel-plugin-transform-decorators-legacy#20]
Is it possible to overwrite the implementation of some method? Overriding the `property` on the `target` does not really overwrite the method, like this:

```
function dec(id) {
    function exec(target, property, descriptor) {
      console.log('Prototype', target.prototype);

      target[property] = function() {
        console.log('executed', id);
      };
    }

    return exec;
}

class Example {
    @dec(1)
    method() {
      console.log('Method called');
    }
}

let example = new Example();

example.method();
```

This code still prints "Method called". Also, there is no `prototype` in `target`.
Is it possible to overwrite the method of the target somehow?

Thanks,

**Comment by loganfsmyth** [comment]
You seem to be misunderstanding decorators a bit. `target` is already the prototype, you wouldn't do `target.prototype`. Secondly, your assignment is working, but the descriptor will be defined after the decorator exits, so your assigned method will be immediately overwritten. You'd want to do

```
descriptor.value = function(){
    console.log('executed', id);
};
```

If you have questions, feel free to drop by Babel's [support channel on Slack](https://slack.babeljs.io/), or #javascript on Freenode.

**Comment by ipeychev** [comment]
Okay, thanks!
