### ISSUE TITLE
Decorators which take in parameters don't work

### ISSUE THREAD

**Issue by inian** [loganfsmyth/babel-plugin-transform-decorators-legacy#21]
I am using [Material-UI](http://www.material-ui.com/) for my react application. 
Here is an example from their [documentation](http://www.material-ui.com/#/customization/themes)
This doesn't work after compiling with this plugin. 

```
import MyRawTheme from 'path/to/your/raw/theme/file';
import ThemeManager from 'material-ui/lib/styles/theme-manager';
import ThemeDecorator from 'material-ui/lib/styles/theme-decorator';
const theme = ThemeManager.getMuiTheme(MyRawTheme);

@ThemeDecorator(theme)
class MyComponent extends Component {
}
export default MyComponent;
```

However this works

```
export default ThemeDecorator(theme)((MyComponent));
```

**Comment by loganfsmyth** [comment]
Please define "doesn't work". What error do you get?

Also thrown off because neither of your exact actually have valid es6 export syntax.

If you can, please make a real example.

**Comment by inian** [comment]
Looks like I was using the wrong decorator from their documentation before! Just found it..
Sorry..my bad!
