### ISSUE TITLE
how to use with webpack

### ISSUE THREAD

**Issue by stukennedy** [loganfsmyth/babel-plugin-transform-decorators-legacy#22]
Apologies ... but I can't figure out how I should enable this plugin in Webpack.
I tried adding it like this

``` js
{
    test: /\.jsx?$/,
    exclude: /node_modules/,
    loader: 'babel',
    query: {
      presets: [
        'es2015',
        'react',
        'stage-0'
      ]
    },
    plugins: ['transform-decorators-legacy']
  }
```

but I still get the error `Decorators are not supported yet in 6.x pending proposal update.`

**Comment by loganfsmyth** [comment]
`plugins` is a sibling of `presets`, it should go inside the `query` block.
