### ISSUE TITLE
Class properties and decorators not playing well

### ISSUE THREAD

**Issue by themouette** [loganfsmyth/babel-plugin-transform-decorators-legacy#24]
I don't have enough insight to determine if this is due to babel 6 transform-class-properties or transform-decorators-legacy, but there is inconsistencies when migrating from babel5 decorators.

I created a sample project to demonstrate it: https://github.com/themouette/demo-decorators-classprops

Static properties are applied to the decorated class instead of the original class.

Current generated code looks like:

``` javascript
// ...
var Test = decorator(_class = function () {
  function Test() {
    _classCallCheck(this, Test);
  }

  _createClass(Test, [{
    key: 'render',
    value: function render() {
      return 'foo';
    }
  }]);

  return Test;
}()) || _class;

Test.propTypes = {
  foo: 'Hello'
};
// ...
```

When it should look someting like:

``` javascript
// ...
_class = function () {
  function Test() {
    _classCallCheck(this, Test);
  }

  _createClass(Test, [{
    key: 'render',
    value: function render() {
      return 'foo';
    }
  }]);

  return Test;
}()) || _class;

_class.propTypes = {
  foo: 'Hello'
};

var Test = decorator(_class);
// ...
```

Am I doing something wrong?

**Comment by loganfsmyth** [comment]
Been meaning to document this in the README, but it slipped my mind. Your transforms are in the wrong order: https://github.com/themouette/demo-decorators-classprops/blob/master/.babelrc#L3

```
"plugins": ["transform-class-properties", "transform-decorators-legacy"]
```

should be

```
"plugins": ["transform-decorators-legacy", "transform-class-properties"]
```

**Comment by themouette** [comment]
Great, thank you.
