### ISSUE TITLE
Decorator bug with target parameter

### ISSUE THREAD

**Issue by rsumilang** [loganfsmyth/babel-plugin-transform-decorators-legacy#25]
Hi Logan - I think I found a bug with the `target` parameter of a decorator. The `target` is supposed to return the class associated for the decorator.

A decorator on the class level works fine, I get an function back that I can instantiate.

A decorator on the method level returns back an `Object` of the class that I cannot instantiate.

``` js
function dec(debug) {
  return (target, property, descriptor) => {
    console.log(debug);
    console.log(target);
  }
}

@dec('from class:')
class A {

  @dec('from method:')
  doSomething(){

  }
}
```

Console output:

```
from method:
> A {}

from class:
> function A () {
   _classCallback(this, A);
}
```

I believe the `target` should be consistent where methods and classes get the same target. The `target` I received from the class level is what's useful to me here since I can't instantiate the other.

Thanks!

**Comment by loganfsmyth** [comment]
The target of a method decorator is the class prototype, not the constructor function.

**Comment by rsumilang** [comment]
Thanks for the quick reply! What about static methods? It seems that they receive a constructor like a class instead of a prototype:

``` js
function dec(debug) {
  return (target, property, descriptor) => {
    console.log(debug);
    console.log(target);
  }
}

class A {

  @dec('from static method:')
  static doSomething(){

  }
}
```

Console:

```
from static method:
> function A () {
   _classCallback(this, A);
}
```

Is this intended functionality?

**Comment by loganfsmyth** [comment]
Yes. A method decorator's target, whether static or non-static, is the object that the property is getting added to. When you specify a non-static method, even without the decorator the method is available at `Constructor.prototype.foo`, with a static method it's at `Constructor.foo`. The decorator just gets whatever object the descriptor will be defined on.

**Comment by rsumilang** [comment]
I see (said the blind man). ;) Thanks for the explanation!

**Comment by loganfsmyth** [comment]
No problem, always feel free to drop by #javascript on Freenode or Babel's Slack if you have more ES6 questions.
