### ISSUE TITLE
class decorator works different from babel5

### ISSUE THREAD

**Issue by goto100** [loganfsmyth/babel-plugin-transform-decorators-legacy#28]
```
function classDecorator(Target) {
  return class DecoratedClass extends Target {
    test() {
      return 'decorated';
    }
  };
}

@classDecorator
class Test {
  static test() {
    return 'original';
  }

  static run() {
    // `Test` is not the *decorated* class here, but it is in bebel 5.
    console.log(Test.test());
  }
}

Test.run();
```

In bebel 5, it will return 'decorated', in this plugin, it return 'original'.

**Comment by loganfsmyth** [comment]
Probably another case of https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/issues/24 where your plugins are in the wrong order?

**Comment by goto100** [comment]
Seems not. I'm not using transform-class-properties, my `.babelrc` file is:

```
{
  "plugins": [
    "transform-decorators-legacy",
    "add-module-exports",
    "transform-es2015-classes",
    "transform-es2015-destructuring",
    "transform-es2015-function-name",
    "transform-es2015-parameters",
    "transform-es2015-sticky-regex",
    "transform-es2015-unicode-regex",
    "transform-es2015-modules-commonjs"
  ]
}
```

**Comment by goto100** [comment]
If I add `use strict` in the head of the test file, I can even use just one single plugin, the problem still happens.

```
'use strict';

function classDecorator(Target) {
  return class DecoratedClass extends Target {
    test() {
      return 'decorated';
    }
  };
}

@classDecorator
class Test {
  static test() {
    return 'original';
  }

  static run() {
    // `Test` is not the *decorated* class here, but it is in bebel 5.
    console.log(Test.test());
  }
}

Test.run();
```

.babelrc

```
{
  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

**Comment by loganfsmyth** [comment]
Ugh, I'm sorry, I misread your issue. This is actually a duplicate of https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/issues/16, not the one I linked to.

The spec currently is just desugaring examples, which supports the current behavior, rather than the Babel 5 behavior, since it says

```
@dec
class Foo {
}
```

should behave like

```
let Foo = (function () {
  class Foo {
  }

  Foo = dec(Foo) || Foo;
  return Foo;
})();
```

**Comment by goto100** [comment]
Sorry for the mistake, the code in this case works fine. So I opened another issue #29, that's the actually problem.
