### ISSUE TITLE
Cannot Decorate Class Properties

### ISSUE THREAD

**Issue by JustinWilabyPrecor** [loganfsmyth/babel-plugin-transform-decorators-legacy#30]
When using `babel-plugin-transform-class-properties` any decorated class property is undefined

``` js
function myDecorator(){
    // Decorate stuff
}
...
class Person{
    @myDecorator
    age = 43; // Nope - doesn't work

    @myDecorator
    toString(){ // Yep - works
    }
    constructor(){
        console.log(this.age) // undefined
    }
}
```

Furthermore, the decorator is never called for the class property.  Am I missing something?

**Comment by maxs15** [comment]
I have the same issue

**Comment by loganfsmyth** [comment]
Please post your Babel configs.

**Comment by JustinWilabyPrecor** [comment]
``` js
{
    "presets": [
        "es2015",
        "stage-0"
    ],
    "plugins": [
        "transform-object-rest-spread",
        "babel-plugin-syntax-jsx",
        "babel-plugin-inferno",
        "babel-plugin-transform-class-properties",
        "babel-plugin-transform-decorators-legacy"
    ]
}
```

**Comment by loganfsmyth** [comment]
Same issue as https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/issues/24, your config has `transform-class-properties` listed before `transform-decorators-legacy`, which is causing problems. Given your config, I'd do

```
{
    "presets": [
        "es2015",
        "stage-0"
    ],
    "plugins": [
        "babel-plugin-syntax-jsx",
        "babel-plugin-inferno",
        "babel-plugin-transform-decorators-legacy"
    ]
}
```

since `stage-0` will cover `transform-object-rest-spread` and `transform-class-properties` for you already.

**Comment by maxs15** [comment]
Problem solved by including babel-plugin-transform-decorators-legacy first ! :)

**Comment by azarus** [comment]
Sorry to post here but i have the same issue and I have the decorators-legacy plugin listed first.
