### ISSUE TITLE
Class-decorator not evaluated on initial render?

### ISSUE THREAD

**Issue by peletiah** [loganfsmyth/babel-plugin-transform-decorators-legacy#38]
I've upgraded from Babel 5 to Babel 6 and use your plugin to build [this react-anything-sortable](http://jasonslyvia.github.io/react-anything-sortable/demo/#/vertical?_k=ewrtzi)-example with gulp and browserify:

``` javascript
import React from 'react';
import Sortable from 'react-anything-sortable';
import { sortable } from 'react-anything-sortable';

@sortable
class DemoHOCItem extends React.Component {
  render() {
    return (
      <div {...this.props}>
        {this.props.children}
      </div>
    );
  }
}

export default DemoHOCItem;

class Test extends React.Component {
  constructor() {
    super();
    this.state = {
      items: ['four','five','six']
    };
  }

render() {
    function renderWithSortable(renderItem, index) {
      return (
        <DemoHOCItem className="vertical" sortData="renderItem" key={index} dynamic>
          {console.log('rendering with sortable')}
          {renderItem+' sortable'}
        </DemoHOCItem>
      );
    }

    return (
      <div className="demo-container">
         <Sortable className="vertical-container" direction="vertical">
          {this.state.items.map(renderWithSortable, this)}
        </Sortable>
      </div>
    );
  }
};

export default Test;
```

On the initial rendering of `<DemoHOCItem/>` I get this warning:

``` javascript
main.js:28024 Warning: Unknown props `sortData`, `onSortableItemMount`, `onSortableItemReadyToMove`, `sortable`, `sortHandle` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by DemoHOCItem)
    in DemoHOCItem (created by SortableItem)
    in SortableItem (created by Test)
    in div (created by Sortable)
    in Sortable (created by Test)
    in div (created by Test)
    in Test (created by RoutingContext)
    in div (created by App)
    in App (created by RoutingContext)
    in RoutingContext (created by Router)
    in Router
```

also when dragging an sortable item for the first time:

``` javascript
main.js:28024 Warning: Unknown prop `isDragging` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by DemoHOCItem)
    in DemoHOCItem (created by SortableItem)
    in SortableItem (created by Test)
```

Subsequent renderings (Without reloading the app) no longer produce warnings, so the sortable-module does its magic.

My guess is that the "sortable"-decorator is not evaluated on the first render, therefore React does not know what to do with all the functions provided by `<div {...this.props}>` in DemoHOCItem.render()

Is there something I can do to get rid of the warning?

**Comment by loganfsmyth** [comment]
Have you filed this issue with that module? It seems more likely to be that they are passing the props down into the child component incorrectly somewhere.

**Comment by peletiah** [comment]
Thanks for the quick reply! Thought it must be the decorator-plugin, as it's a simple object-spread in DemoHOCItem which causes the warning (Didn't counter-check without the module though).  I've now filed a [report](https://github.com/jasonslyvia/react-anything-sortable/issues/58) with them too now.

**Comment by peletiah** [comment]
[Add warning for unknown properties on DOM elements](https://github.com/facebook/react/pull/6800) was introduced in React 15.2.0 (Which I happened to update at the same time as Babel). So as you assumed, it's the [Sortable-module](https://github.com/jasonslyvia/react-anything-sortable), not this Babel-plugin.
