### ISSUE TITLE
Not working with mobx simple app

### ISSUE THREAD

**Issue by andreyluiz** [loganfsmyth/babel-plugin-transform-decorators-legacy#39]
I am working on [a project using mobx + react](https://github.com/andreyluiz/react-mobx). And I need to use decorators. But I am getting an `Uncaught TypeError: decorator is not a function` in the Chrome console after Webpack bundle. Webpack shows no errors. 

My webpack loader.

```
{
  test: /\.js$/,
  exclude: /(node_modules|bower_components)/,
  loader: 'babel', // 'babel-loader' is also a legal name to reference
  cacheDirectory: true,
  query: {
    plugins: [
      "transform-decorators-legacy",
    ],
    presets: ['react', 'es2015', 'stage-1']
  }
}
```

My dependencies:

```
"devDependencies": {
  "babel-cli": "^6.10.1",
  "babel-core": "^6.10.4",
  "babel-loader": "^6.2.4",
  "babel-plugin-transform-decorators-legacy": "^1.3.4",
  "babel-preset-es2015": "^6.9.0",
  "babel-preset-react": "^6.11.1",
  "babel-preset-stage-1": "^6.5.0",
  "mobx": "^2.3.6",
  "mobx-react": "^3.5.0",
  "react": "^15.2.1",
  "react-dom": "^15.2.1",
  "webpack": "^1.13.1"
}
```

Some further investingation points to this plugin. The errors pops out in the `_applyDecoratedDescriptor` method.

Am I missing something?

**Comment by loganfsmyth** [comment]
`@computed` does not exist, did you forget to import it? https://github.com/andreyluiz/expert-invention/blob/master/app/js/root.js#L6

**Comment by andreyluiz** [comment]
Right. Computed is not declared. But even if I import it the error persists. And if it was something about undeclared dependency, webpack would scream during the compilation, right?

**Comment by loganfsmyth** [comment]
Not necessarily. You are using Babel's module processing, not Webpack 2's, and Babel doesn't know how files relate to eachother.

The error itself means something that you've passed via `@<some-decorator>` is not a function.

**Comment by andreyluiz** [comment]
Hmm, that's weird. I'll close it for now. I'm still not able to run it but I know the problem is something related with my imports or dependencies. Thank you for the help. :)

**Comment by jhchill666** [comment]
@andreyluiz did you figure this out?  stuck on exactly the same issue and haven't a clue whats going on

**Comment by deangibson89** [comment]
Just mentioning here that I got this as well when I tried to import `observable` from `mobx-react`. When I changed it to just `mobx` it worked. i.e.: `import { observable } from 'mobx';`

**Comment by andreyluiz** [comment]
Ah, sorry guys. I've deleted the repo. But I will create a new simulation and give another try. If it works okay I close this issue. :)

**Comment by andreyluiz** [comment]
Guys, I've created [another repo](https://github.com/andreyluiz/react-mobx).

As @Tiwaz89 said, the imports are wrong. 

`@observable` and `@computed` belongs to `mobx` package (it's obvious).
`@observer` belongs to the `mobx-react` package.

MobX documentation for [`@observable`](https://mobxjs.github.io/mobx/refguide/observable-decorator.html), [`@computed`](https://mobxjs.github.io/mobx/refguide/computed-decorator.html) and [`@observer`](https://mobxjs.github.io/mobx/refguide/observer-component.html) are very clear and brings an example right in the top of the article.
