### ISSUE TITLE
decorator breaks class name resolving in static properties

### ISSUE THREAD

**Issue by breezewish** [loganfsmyth/babel-plugin-transform-decorators-legacy#40]
this works:

``` js
class MyClass {
    static MY_CONSTANT = 'foo';
    static MY_ANOTHER_CONSTANT = {
        [MyClass.MY_CONSTANT]: 'bar',
    };
}
```

but it won't work after enabling `transform-decorators-legacy`: Cannot read property 'MY_CONSTANT' of undefined.

**Comment by loganfsmyth** [comment]
Yup, this is a dup of https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/issues/17 Haven't had time to fix it yet, but it's a known issue.

**Comment by breezewish** [comment]
Oh. Thanks, haven't noticed that
