### ISSUE TITLE
Wrong? target with class functions decorators

### ISSUE THREAD

**Issue by mcasimir** [loganfsmyth/babel-plugin-transform-decorators-legacy#42]
For class functions decorators the target argument is not an actual reference to the real class but a reference to an instance, sounds weird to me. Is it correct/intended?

``` js
let assert = require('assert');
let fnTarget = null;
let fnTargetConstructor = null;

function fnDec(target, methodName, descriptor) {
  fnTarget = target;
  fnTargetConstructor = target.constructor;
  return descriptor;
}

class A {
  @fnDec
  doSomething() {}
}

assert(fnTarget !== A);
assert(fnTargetConstructor === A);
```

My `package.json`:

``` json
    "babel-core": "^6.11.4",
    "babel-plugin-transform-decorators-legacy": "1.3.4"
```

My `.babelrc`:

``` json
{
  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

**Comment by loganfsmyth** [comment]
`fnTarget === A.prototype` :)

**Comment by mcasimir** [comment]
I see.. now it makes much more sense :). Sorry for the silly report.
Thanks!

**Comment by loganfsmyth** [comment]
No problem. If you had `static doSomething(){}` it would be what you thought, but then your other one would be wrong.
