### ISSUE TITLE
When initializer runs

### ISSUE THREAD

**Issue by vnesterovsky** [loganfsmyth/babel-plugin-transform-decorators-legacy#46]
It's a little unclear as to when instance members' initializers are run.
There are two functions in the transpiled code: `_initDefineProp`, and `_applyDecoratedDescriptor`.
Both may run initializers.
While the `_initDefineProp` runs initializer with `this` bound to a class instance, 
the `_applyDecoratedDescriptor` runs initializer (if it decides to run it) with `this` bound to a class constructor function.

E.g. I was trying to create a decorator `@BindThis` that would bind function to `this` instance during construction.

`class My
{
  @BindThis()
  mouseclick(e) {...}
}`

BindThis had to replace value with initializer like this:
  'function() { return originalFn.bind(this); }'

Unfortunately this initializer is called at _applyDecoratedDescriptor where `this` is constructor.

Can you please clarify?
Thanks.

**Comment by loganfsmyth** [comment]
Perhaps you'd be best off using an existing decorator like [`autobind`](https://github.com/jayphelps/core-decorators.js/blob/master/src/autobind.js)?
