### ISSUE TITLE
Repetitive code in each module

### ISSUE THREAD

**Issue by jeron-diovis** [loganfsmyth/babel-plugin-transform-decorators-legacy#49]
Is there any chance that this transform will be smart enough to keep it's code in separate module, like ["transform-runtime"](https://babeljs.io/docs/plugins/transform-runtime/) does?

Of course, it's not necessary to joyfully use it – just to be, you know, and ideal tool =)

**Comment by loganfsmyth** [comment]
It's a tough one to solve since Babel doesn't currently provide a way to do this easily. It is something I'm keeping in mind for the future though. For now, I'd hope that by the time the file is gzipped, the difference in size wouldn't be super noticeable.

**Comment by loganfsmyth** [comment]
We're planning to move this into Babel as `babel-plugin-transform-decorators` in Babel 7.x, which will mean this code will end up in `babel-runtime` like the other code Babel stuff, so closing this.

**Comment by jharris4** [comment]
Just noticed the duplication of the code myself. Any word on `babel-plugin-transform-decorators` in Babel 7.x?

**Comment by jharris4** [comment]
Looks like it might actually be a part of Babel 7 now?

https://www.npmjs.com/package/babel-plugin-transform-decorators

https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-decorators

I guess we could switch to that if we're willing to move to Babel 7?

**Comment by blikblum** [comment]
Hi, 

@loganfsmyth 

I noticed that babel-plugin-proposal-decorators migrated the helpers to babel-helpers in https://github.com/babel/babel/pull/7017

Any chance this can be done to the legacy also?
