### ISSUE TITLE
Decorators in source code

### ISSUE THREAD

**Issue by TheRusskiy** [loganfsmyth/babel-plugin-transform-decorators-legacy#50]
The source code includes @decorators, which are not officially supported by babel and the only way to make them work is by introducing "babel-plugin-transform-decorators-legacy".
Can we please rewrite code to include them in a more vanilla style?

**Comment by loganfsmyth** [comment]
I'm not sure what you're asking for. What would be a more vanilla style? Why is style important in this case?

**Comment by TheRusskiy** [comment]
@loganfsmyth lol, sorry, I created issue on the wrong project.
The other project was a NPM package which had decorators in source code, so you had to use babel and this plugin with it. Probably had 2 tabs open at the same time and posted to the wrong one.
Once again, sorry!

**Comment by loganfsmyth** [comment]
Ahh, that makes sense haha. I agree, modules published to npm should be compiled before publishing.
