### ISSUE TITLE
Decorators in Object Literal Method Declaration

### ISSUE THREAD

**Issue by 0xMarkian** [loganfsmyth/babel-plugin-transform-decorators-legacy#53]
The [spec](https://github.com/wycats/javascript-decorators#object-literal-accessor-declaration) says that decorators have to support syntax like this:
```javascript
var o = {
  @F("color")
  @G
  bar() { }
}
```

But in fact the transformer doesn't do any transformation(decorations).

**Comment by loganfsmyth** [comment]
Do you have a specific example? It does definitely cover that: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/blob/master/test/index.js#L1147

**Comment by 0xMarkian** [comment]
Sorry, didn't read the spec completely - my mistake. I am going to close this issue.
