### ISSUE TITLE
getting a `_dec is not a function` error

### ISSUE THREAD

**Issue by cowchimp** [loganfsmyth/babel-plugin-transform-decorators-legacy#55]
Hi.

Trying to use this plugin. I'm probably doing something wrong.

I created a gist with a simplified test case
https://gist.github.com/cowchimp/fd1f2d19ba55997d371e861d09ddd76f
When I try to use a class decorator I get a `_dec is not a function` error.
When I comment out the line with the use of the decorator `foo` everything works.

Can you please let me know what I'm doing wrong?

Thanks.

**Comment by loganfsmyth** [comment]
That is expected behavior. When you do

```
@foo('.')
class Foo {}
```

it is the same as doing


```
var fn = foo('.');

@fn
class Foo {}
```

meaning you are calling your `dec` function, but it is not returning a decorator function, when it should. In this case `fn === undefined` because your `foo` function logs the argument, but returns nothing.
