### ISSUE TITLE
String literal properties

### ISSUE THREAD

**Issue by bathos** [loganfsmyth/babel-plugin-transform-decorators-legacy#6]
Glad to have found this! There's a case where it's failing for me, which is when a method name is quoted (due to being a reserved word). I'm not familiar with Babel internals so I don't know exactly where this occurs but I think it may be [here](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/blob/master/src/index.js#L159) -- looks like it expects property names to always be naked string literals?

**Comment by bathos** [comment]
That was pretty simple: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/pull/7

That PR lets numeric & quoted-string property names work. Computed property names still won't, however.

**Comment by loganfsmyth** [comment]
Heya, thanks for the PR! Did Babel 5 support decorating computed properties? I'd need Babylon to support parsing decorated computed properties before this could support them.

**Comment by loganfsmyth** [comment]
Landed the PR.

**Comment by bathos** [comment]
Come to think of it, I don't think it did (support computed props I mean) -- probably because of the grammar ambiguity of []? So there's no need to try, assuming the objective here is just to match Babel 5’s old behavior.
