### ISSUE TITLE
async method named "get"

### ISSUE THREAD

**Issue by icodeforlove** [loganfsmyth/babel-plugin-transform-decorators-legacy#61]
When you name a async method `get` and try to decorate it, it will get called whenever it is referenced and not function as expected.

```javascript
let decorator = target => {
    return target;
};

class Example {
	@decorator async get () {
		console.log('called');
	}
}

let instance = new Example();
typeof instance.get;
```

**Comment by loganfsmyth** [comment]
This is a bug in your `decorator` function. If you comment out your `return target;` it will work as you expect. You are returning `target`, which is `Example.prototype`, not the function. Because you return the prototype object, it is processed like a property descriptor and will convert your `get` function into a getter property.

Property descriptors take 3 arguments. you're supposed to replace the third one, not the first.
```
let decorator = (target, property, descriptor) => {
  return descriptor;
}
```

**Comment by icodeforlove** [comment]
How come this functions differently?


```javascript
let decorator = target => {
    return target;
};

class Example {
	@decorator async get_ () {
		console.log('called');
	}
}

let instance = new Example();
typeof instance.get_;
```

**Comment by icodeforlove** [comment]
Your solution does work but not for function decorators

```javascript
let decorator = () => {
	return (target, key) => {
		// how can i set something on the target without returning the target?
	};
};

class Example {
	@decorator() async get () {
		console.log('called');
	}
}

let instance = new Example();
typeof instance.get;
```

**Comment by loganfsmyth** [comment]
The return value of a decorator function is a property descriptor, like you'd pass to [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) so the important keys are `configurable`, `enumerable`, `value`, `writable`, `get`, and `set`.

When you rename it to `get_` your decorator is passing a descriptor that does nothing. Note that now `typeof instance.get_ === undefined`.

**Comment by icodeforlove** [comment]
```javascript
let decorator = target => {
    return target;
};

class Example {
	@decorator async get_ () {
		console.log('called');
	}
}

let instance = new Example();

console.log(typeof instance.get_);
```

I get `function`, maybe I have a bad babel config?

**Comment by icodeforlove** [comment]
Oh I see, so those keys are reserved and are expected to cause issues? Due to how we detect property descriptors?

`get`, and `set` cause issues. `configurable` , `value`, and `writable` are fine

**Comment by loganfsmyth** [comment]
Oh you're right about `function` in that case, that's probably just an extreme edge case in the spec then.

If you wanted to replace the function, the easiest option would be to do

```
let decorator = (target, property, descriptor) => {
	descriptor.value = function() {
		// how can i set something on the target without returning the target?
	};
        return descriptor;
};
```

**Comment by icodeforlove** [comment]
Thanks, this is the best way to do it!
