### ISSUE TITLE
Class property decorator hack.

### ISSUE THREAD

**Issue by IAIAE** [loganfsmyth/babel-plugin-transform-decorators-legacy#70]
write a Class below, and add a `log` decorator to a instance method.

```javascript
function log(target, key, descriptor){
	let method = descriptor.initializer();
	let _method = function(){
		let context = this;
		return function(){
			console.info('the log descriptor::', key);
			method.apply(context, arguments);
		}
	}
	descriptor.initializer = _method;
	return descriptor;
}

Class Test{
	name = 'hello world';

	@log
	show = () =>{
		console.info(this.name)   
	}
}
```

cannot get `this` in `show`. cause the compiled code is:

```javascript
_descriptor = _applyDecoratedDescriptor(_class2.prototype, 'show', [log], {
        enumerable: true,
        initializer: function initializer() {
            var _this3 = this;
            return function() {
                console.info(_this3.name);
            }
            ;
        }
    })),
```

the `_this3` in this function is the Class. not the instance.

can any solution???   thx all.

**Comment by loganfsmyth** [comment]
`descriptor.initializer();` calls the initializer in the wrong place. You need to call `initializer` inside of `_method`.

**Comment by IAIAE** [comment]
@loganfsmyth  I mean, 

no matter what i do in descriptor function `log`.  the Babel compile the code like below: 
```javascript
_descriptor = _applyDecoratedDescriptor(_class2.prototype, 'show', [log], {
        enumerable: true,
        initializer: function initializer() {
            var _this3 = this;
            return function() {
                console.info(_this3.name);
            }
            ;
        }
    })),
```
so,  the `this` in `show` 'bind' to `_this3` after compiled, `_this3` is not the reference of instance, but the reference of class.prototype.  thus, `console.info(this.name)` return undefined. 

is there any method to solve this problem?

**Comment by borela** [comment]
Write it as a method or assign a function instead of an arrow function:
```js
	@log
	show(){
		console.info(this.name)   
	}

	@log
	show = function(){
		console.info(this.name)   
	}

**Comment by IAIAE** [comment]
@borela thx a lot
