### ISSUE TITLE
About the parameter decorator support

### ISSUE THREAD

**Issue by itfinally** [loganfsmyth/babel-plugin-transform-decorators-legacy#73]
Hello, I have a question for babel-plugin-transform-decorators-legacy.

I wrote a http client by typescript, this is the [demo](https://github.com/itfinally/RetrofitJs/blob/master/test/te2.js).

It can working on typescript because there are support class/method/parameter/attribute decorator.
And I want to support es6 too, but this is a part of compiled code.

`function upload(file, name) {}`

Seem like babel-plugin-transform-decorators-legacy not support decorate parameter ? = =||

**Comment by loganfsmyth** [comment]
This plugin implements the original decorator behavior of Babel 5, and that is all. I don't know what the current status of parameter decorators is in general, or if there is any plan to support them as an ES20XX proposal.
