### ISSUE TITLE
Hook into initializer

### ISSUE THREAD

**Issue by osi-oswald** [loganfsmyth/babel-plugin-transform-decorators-legacy#74]
How can I hook into the initializer? Right now there is no way I could react to the initialized value, for example to keep two properties synced.

```js
function syncToBar(target, key, descriptor) {
  let _value = descriptor.initializer();
  
  return {
    enumerable: true,
    configurable: true,
    get() { return _value; },
    set(value) {
      // not called for the initial value :-(
      this.bar = _value = value;
    }
  }
}

class MyClass {
  @syncToBar foo = 1;
  bar;

  constructor() {
    console.log(this.bar); // -> undefined, but I want it to be 1 :-(
    this.foo = 2;
    console.log(this.bar); // -> 2, OK (synced)
  }
}
```

Looking at the emitted code from `transform-decorators-legacy`, I can see no way to initialize `bar` with the initial value from `foo` with just the decorator. Am I missing something?

**Comment by osi-oswald** [comment]
This is how `syncToBar` would look like in TypeScript emitted decorators/initializers. It just works without the need for any "special" `initializer`.
```js
function syncToBar(target, key) {
  let _value;
  return {
    enumerable: true,
    configurable: true,
    get() { return _value; },
    set(value) {
      // also called for the initial value
      this.bar = _value = value;
    }
  }
}
```

**Comment by osi-oswald** [comment]
Just figured, `buildInitializerDefineProperty ` could be changed to this:
```js
const buildInitializerDefineProperty = template(`
    function NAME(target, property, descriptor, context){
        if (!descriptor || !descriptor.initializer) return;
        context[property] = descriptor.initializer.call(context);
    }
`);
```
That way a setter defined on the prototype has a chance to react to the initialization assignment, whereas using `Object.defineProperty` will just skip the setter on the prototype :-/

**Comment by osi-oswald** [comment]
If I take a closer look at [babel-plugin-transform-class-properties](https://www.npmjs.com/package/babel-plugin-transform-class-properties), I can see it has an option `spec`, which by default is false. If option `spec` is false (default), an assignment is emitted. And only of if  `spec` is  true, it will use `Object.defineProperty` to initialize.

Therefore: The default should be what I proposed in my last comment. And if one would be fancy, either read somehow the `spec` option from `transform-class-properties` or provide an own `spec` option to still emit `Object.defineProperty` for initialization.

**Comment by loganfsmyth** [comment]
`spec` exists because it is what the spec dictates, and it will default to `true` in future versions of Babel. The goal of this plugin is to mimic the behavior of decorators as they were implemented in Babel 5. I'm not looking to add enhancements like this.

What you want should be doable in future versions of the decorators spec, but implementing that is beyond the scope of this plugin. Until then, maybe you can get what you want by defining it as `@syncFromFoo` instead?
