### ISSUE TITLE
A issue in React-Native

### ISSUE THREAD

**Issue by wsxiaoluob** [loganfsmyth/babel-plugin-transform-decorators-legacy#82]
After i import babel-plugin-transform-decorators-legacy,i can't open my project any more.
when i run 'react-native run-ios',a error appeared:

**error: bundling failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null**

in package.json, devDependencies is 
**"babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "babel-preset-stage-1": "^6.24.1",**

did i miss something ?

**Comment by loganfsmyth** [comment]
It is hard to say without the rest of the error message. The stack trace will give more information, please include it.

**Comment by wsxiaoluob** [comment]
@loganfsmyth Thanks.
I fixed this problem with upgrade babel to 7.0.0-beta.47.

**Comment by loganfsmyth** [comment]
@wsxiaoluob This plugin is only for Babel 6. See https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy#babel--7x
