### ISSUE TITLE
v1.3.0 seems broken

### ISSUE THREAD

**Issue by elierotenberg** [loganfsmyth/babel-plugin-transform-decorators-legacy#9]
Hello @loganfsmyth, thanks again for your dedication.

It seems that v1.3.0 may be broken, related to importing `_Object$defineProperty`.

In [this gist](https://gist.github.com/elierotenberg/f781c5821b0f36965ae2) you will find my original test source, and its transpiled version with v1.2.0 and v1.3.1. In the output of v1.3.0, the following line is present:

``` js
import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
```

I get the following error when I run the file:

```
import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
```

I've checked my babel config and `babel-plugin-transform-es2015-modules-commonjs` is after `babel-plugin-transform-decorators-legacy` though. v1.2.0 still works fine for the given example.

Any idea what could cause this? Is there any way I can contribute?

**Comment by loganfsmyth** [comment]
Interesting. What does your config look like? It seems like the runtime-injected import isn't processed by the module transform

**Comment by loganfsmyth** [comment]
Pushed a temporary fix. I think a real fix will require changes to Babel but we'll see.

**Comment by elierotenberg** [comment]
I used 4 slightly different setups (node dev, node prod, browser dev, browser prod), but all cause the same issue.

[Here's the most simple one](https://github.com/elierotenberg/lib-starterkit/blob/79268ff89f947268a78e49e6c3123e94f521749d/config/babel/browser/dev/index.js).

**Comment by loganfsmyth** [comment]
Let me know if you have any issues with 1.3.1, I think it should be enough for now.

**Comment by elierotenberg** [comment]
Works like a charm. Thank you sir!

**Comment by idolize** [comment]
**I'm still hitting this issue with version `1.3.4`** :cry: 

My `.babelrc` looks similar, but I'm using the `"presets"` section instead of listing out every individual plugin for `es2015`.

``` js
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["transform-decorators-legacy", "transform-runtime"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    }
  }
}
```

**Comment by loganfsmyth** [comment]
@idolize Can you make a reproducible example? Hard to say without something to test with. You may also just be running into https://phabricator.babeljs.io/T6922.

**Comment by idolize** [comment]
Hmm, doesn't the issue you linked essentially say that the entire `transform-runtime` plugin is currently unusable as of now, or am I misunderstanding? I haven't tested without any of my decorator code, but I can do that to help narrow things down.

**Comment by alex94puchades** [comment]
I'm having same issue with v1.3.4 and almost same config as @idolize
